language: php
sudo: false

php:
  - 7.1
fast_finish: true

before_script:
  - composer install --prefer-dist

script:
  - bin/phpunit --testsuite=unit -v $PHPUNIT_FLAGS

after_success:
  php bin/coveralls -v
  wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
